# Generated by Django 5.1.3 on 2024-11-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event', max_length=200)),
                ('description', models.TextField(help_text='Description of the event')),
                ('location', models.CharField(help_text='Event location', max_length=255)),
                ('start_date', models.DateTimeField(help_text='Event start date and time')),
                ('end_date', models.DateTimeField(help_text='Event end date and time')),
                ('speakers', models.TextField(blank=True, help_text='List of speakers at the event', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when event is created')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(help_text='Type of the ticket (e.g., VIP, Regular).', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of this ticket.', max_digits=8)),
                ('quantity', models.PositiveIntegerField(help_text='The total quantity of this ticket type available for sale.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when ticket type was created.')),
                ('event', models.ForeignKey(help_text='The event this ticket is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the attendee registered.')),
                ('user', models.ForeignKey(help_text='The user who is attending the event.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(help_text='The event the attendee has registered for.', on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event')),
                ('ticket', models.ForeignKey(help_text='The ticket type the attendee has purchased.', on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.ticket')),
            ],
        ),
    ]
