# Generated by Django 5.1.3 on 2024-11-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_payment',
            field=models.BooleanField(default=False, help_text='Does the event require payment?'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price of this ticket.', max_digits=8, null=True),
        ),
    ]
