# Generated by Django 5.1.3 on 2024-11-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_requires_payment_alter_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='requires_payment',
        ),
        migrations.AddField(
            model_name='ticket',
            name='requires_payment',
            field=models.BooleanField(default=False, help_text='Does this ticket type require payment?'),
        ),
    ]
