# Generated by Django 5.1.3 on 2024-11-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_requires_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requires_payment',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Does this ticket type require payment?'),
        ),
    ]
