# Generated by Django 5.1.3 on 2024-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requires_payment',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Does this ticket type require payment?', max_length=3),
        ),
    ]
