# Generated by Django 5.1.3 on 2024-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_ticket_requires_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requires_payment',
            field=models.BooleanField(default=False, help_text='Does this ticket type require payment?'),
        ),
    ]
