# Generated by Django 5.1.3 on 2024-11-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_ticket_requires_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requires_payment',
            field=models.BooleanField(default=True, help_text='Check if this ticket requires payment.'),
        ),
    ]
