# Generated by Django 5.1.3 on 2024-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_razorpay_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='razorpay_account_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_page_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
