# Generated by Django 5.1.3 on 2024-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_razorpay_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_page_url',
        ),
        migrations.AddField(
            model_name='event',
            name='payment_page_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
