# Generated by Django 5.1.3 on 2024-11-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
