# Generated by Django 5.1.3 on 2024-11-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='registration_status',
            field=models.BooleanField(default=False, help_text="Has the attendee's registration been confirmed?"),
        ),
    ]
