# Generated by Django 5.1.3 on 2024-11-23 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_attendee_registration_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendee',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event'),
        ),
    ]
